config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :users
  resources :genres
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/genre.rb
class Genre < ApplicationRecord
  self.primary_key = "genre_id"
  has_many :question
end

app/models/question.rb
class Question < ApplicationRecord
  self.primary_key = "question_id"
  belongs_to :genre
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  self.primary_key = "user_id"
  has_many :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[ show edit update destroy ]

  # GET /genres or /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1 or /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres or /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: "Genre was successfully created." }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: "Genre was successfully updated." }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre.destroy!

    respond_to do |format|
      format.html { redirect_to genres_path, status: :see_other, notice: "Genre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.expect(genre: [ :genre_id, :genre_name ])
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy!

    respond_to do |format|
      format.html { redirect_to questions_path, status: :see_other, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.expect(question: [ :question_id, :question_stantement, :explanation, :user_id, :genre_id, :choices1, :choices2, :choices3, :choices4 ])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: [ :user_id, :user_name, :mail, :password ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |form| %>
  <% if genre.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :genre_id, style: "display: block" %>
    <%= form.number_field :genre_id %>
  </div>

  <div>
    <%= form.label :genre_name, style: "display: block" %>
    <%= form.text_field :genre_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/genres/_genre.html.erb
<div id="<%= dom_id genre %>">
  <p>
    <strong>Genre:</strong>
    <%= genre.genre_id %>
  </p>

  <p>
    <strong>Genre name:</strong>
    <%= genre.genre_name %>
  </p>

</div>

app/views/genres/edit.html.erb
<% content_for :title, "Editing genre" %>

<h1>Editing genre</h1>

<%= render "form", genre: @genre %>

<br>

<div>
  <%= link_to "Show this genre", @genre %> |
  <%= link_to "Back to genres", genres_path %>
</div>

app/views/genres/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Genres" %>

<h1>Genres</h1>

<div id="genres">
  <% @genres.each do |genre| %>
    <%= render genre %>
    <p>
      <%= link_to "Show this genre", genre %>
    </p>
  <% end %>
</div>

<%= link_to "New genre", new_genre_path %>

app/views/genres/new.html.erb
<% content_for :title, "New genre" %>

<h1>New genre</h1>

<%= render "form", genre: @genre %>

<br>

<div>
  <%= link_to "Back to genres", genres_path %>
</div>

app/views/genres/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @genre %>

<div>
  <%= link_to "Edit this genre", edit_genre_path(@genre) %> |
  <%= link_to "Back to genres", genres_path %>

  <%= button_to "Destroy this genre", @genre, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "D Han" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <% if question.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :question_id, style: "display: block" %>
    <%= form.number_field :question_id %>
  </div>

  <div>
    <%= form.label :question_stantement, style: "display: block" %>
    <%= form.textarea :question_stantement %>
  </div>

  <div>
    <%= form.label :explanation, style: "display: block" %>
    <%= form.textarea :explanation %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :genre_id, style: "display: block" %>
    <%= form.number_field :genre_id %>
  </div>

  <div>
    <%= form.label :choices1, style: "display: block" %>
    <%= form.text_field :choices1 %>
  </div>

  <div>
    <%= form.label :choices2, style: "display: block" %>
    <%= form.text_field :choices2 %>
  </div>

  <div>
    <%= form.label :choices3, style: "display: block" %>
    <%= form.text_field :choices3 %>
  </div>

  <div>
    <%= form.label :choices4, style: "display: block" %>
    <%= form.text_field :choices4 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div id="<%= dom_id question %>">
  <p>
    <strong>Question:</strong>
    <%= question.question_id %>
  </p>

  <p>
    <strong>Question stantement:</strong>
    <%= question.question_stantement %>
  </p>

  <p>
    <strong>Explanation:</strong>
    <%= question.explanation %>
  </p>

  <p>
    <strong>User:</strong>
    <%= question.user_id %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= question.genre_id %>
  </p>

  <p>
    <strong>Choices1:</strong>
    <%= question.choices1 %>
  </p>

  <p>
    <strong>Choices2:</strong>
    <%= question.choices2 %>
  </p>

  <p>
    <strong>Choices3:</strong>
    <%= question.choices3 %>
  </p>

  <p>
    <strong>Choices4:</strong>
    <%= question.choices4 %>
  </p>

</div>

app/views/questions/edit.html.erb
<% content_for :title, "Editing question" %>

<h1>Editing question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Show this question", @question %> |
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Questions" %>

<h1>Questions</h1>

<div id="questions">
  <% @questions.each do |question| %>
    <%= render question %>
    <p>
      <%= link_to "Show this question", question %>
    </p>
  <% end %>
</div>

<%= link_to "New question", new_question_path %>

app/views/questions/new.html.erb
<% content_for :title, "New question" %>

<h1>New question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @question %>

<div>
  <%= link_to "Edit this question", edit_question_path(@question) %> |
  <%= link_to "Back to questions", questions_path %>

  <%= button_to "Destroy this question", @question, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :user_name, style: "display: block" %>
    <%= form.text_field :user_name %>
  </div>

  <div>
    <%= form.label :mail, style: "display: block" %>
    <%= form.text_field :mail %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>User:</strong>
    <%= user.user_id %>
  </p>

  <p>
    <strong>User name:</strong>
    <%= user.user_name %>
  </p>

  <p>
    <strong>Mail:</strong>
    <%= user.mail %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>